# Language and versions
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip

# Pip installs
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -e .
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

# Run scripts
script:
  - nosetests test/ -v --with-coverage

# Push the results back to codecov
after_success:
  - codecov

# Notification configuration
notifications:
  irc: false
  email: false
